# Generated by Django 4.1 on 2022-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('firmname', models.CharField(max_length=100)),
                ('firmaddress', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('aadharno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('panno', models.CharField(max_length=15)),
                ('gstno', models.CharField(max_length=15)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='farmerinfo',
            old_name='Address',
            new_name='address',
        ),
    ]
