# Generated by Django 4.1 on 2022-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0004_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquirydate',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirytext',
            field=models.TextField(),
        ),
    ]
